name: Build and deploy Node.js app to Azure Web App - test-react-project

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Check build directory
        run: |
          echo "Checking build directory contents"
          dir build/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-app
          path: build/

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: test-app
          path: ./test-app
          
      - name: List artifact directory contents
        run: |
          echo "Contents of artifact directory:"
          dir ./test-app  

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test-react-project'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E1A582D6B9C7422AA44623EB7CA74A41 }}
